services:
  rabbitmq:
    hostname: RabbitMQ
    image: rabbitmq:3.8.9-management
    container_name: rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=1234
    ports:
        - "5672:5672"
        - "15672:15672"